name: CI
on:
  pull_request:
    branches:
      - main # change this to your default branch name
  push:
    branches:
      - main # change this to your default branch name
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install
        working-directory: ./hmns-app

      - name: Debug Node.js Version
        run: node --version
        working-directory: ./hmns-app

      - name: List Files
        run: ls -R
        working-directory: ./hmns-app

      - name: Run ESLint
        run: npm run lint
        working-directory: ./hmns-app

      - name: Run Tests
        run: npm test
        working-directory: ./hmns-app
