name: CI
on:
  pull_request:
    branches:
      - main # change this to your default branch name
  push:
    branches:
      - main # change this to your default branch name
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
        working-directory: ./hmns-app
      - run: npm run lint
        working-directory: ./hmns-app
      - run: npm test
        working-directory: ./hmns-app
